### ISSUE TITLE
Installer doesn't work on machines that aren't en_US

### ISSUE THREAD

**Issue by cubehouse** [OSVR/OSVR-HDK-Windows-Drivers#5]
My machine's language is en_GB, and the installer gives me this message:

![language](https://cloud.githubusercontent.com/assets/364237/11041009/2341a972-8707-11e5-9db5-9a21e0dadcc3.png)

Please update the installer to work outside of one language setting.

**Comment by rpavlik** [comment]
Hmm, that is a problem indeed.  Looks like that's a `dpinst` issue - was under the impression that it would fall back to internal localizations if there wasn't an overridden one explicitly specified.

For now, as a workaround, you can download the zip file with the inf files, and point "Update Driver" to that folder.

**Comment by rpavlik** [comment]
I think I have fixed this issue: please try https://github.com/OSVR/OSVR-HDK-Windows-Drivers/releases/tag/v1.2.5

**Comment by cubehouse** [comment]
Hi,

Thank you for the fast fix!
Can confirm this now works on my machine.

Many thanks
